ALTER FUNCTION addannouncement (integer, character varying, character varying, character varying, character varying, timestamp without time zone, character varying) OWNER TO test;
ALTER FUNCTION getlinks (integer) OWNER TO test;
ALTER FUNCTION getannouncements (integer) OWNER TO test;
ALTER FUNCTION getevents (integer) OWNER TO test;
ALTER FUNCTION getmodulesettings (integer) OWNER TO test;
ALTER FUNCTION gethtmltext (integer) OWNER TO test;
ALTER FUNCTION getauthroles (integer, integer) OWNER TO test;
ALTER FUNCTION getcontacts (integer) OWNER TO test;
ALTER FUNCTION getmoduledefinitions (integer) OWNER TO test;
ALTER FUNCTION getportalroles (integer) OWNER TO test;
ALTER FUNCTION getrolemembership (integer) OWNER TO test;
ALTER FUNCTION getrolesbyuser (character varying) OWNER TO test;
ALTER FUNCTION getsingleannouncement (integer) OWNER TO test;
ALTER FUNCTION getsinglecontact (integer) OWNER TO test;
ALTER FUNCTION getsingledocument (integer) OWNER TO test;
ALTER FUNCTION getsingleevent (integer) OWNER TO test;
ALTER FUNCTION getsinglelink (integer) OWNER TO test;
ALTER FUNCTION getsinglemoduledefinition (integer) OWNER TO test;
ALTER FUNCTION getsinglerole (integer) OWNER TO test;
ALTER FUNCTION getsingleuser (character varying) OWNER TO test;
ALTER FUNCTION getusers () OWNER TO test;
ALTER FUNCTION gettabs (integer) OWNER TO test;
ALTER FUNCTION getmodulemoduledefinitions (integer) OWNER TO test;
ALTER FUNCTION getportalsettings (character varying, integer) OWNER TO test;
ALTER FUNCTION addcontact (integer, character varying, character varying, character varying, character varying, character varying, character varying) OWNER TO test;
ALTER FUNCTION addevent (integer, character varying, character varying, timestamp without time zone, character varying, character varying) OWNER TO test;
ALTER FUNCTION addlink (integer, character varying, character varying, character varying, character varying, integer, character varying) OWNER TO test;
ALTER FUNCTION addmodule (integer, integer, character varying, character varying, integer, integer, character varying, boolean) OWNER TO test;
ALTER FUNCTION addmoduledefinition (integer, character varying, character varying, character varying) OWNER TO test;
ALTER FUNCTION addrole (integer, character varying) OWNER TO test;
ALTER FUNCTION addtab (integer, character varying, integer, character varying, character varying) OWNER TO test;
ALTER FUNCTION adduser (character varying, character varying, character varying) OWNER TO test;
ALTER FUNCTION updatelink (integer, character varying, character varying, character varying, character varying, integer, character varying) OWNER TO test;
ALTER FUNCTION updateannouncement (integer, character varying, character varying, character varying, character varying, timestamp without time zone, character varying) OWNER TO test;
ALTER FUNCTION updatecontact (integer, character varying, character varying, character varying, character varying, timestamp without time zone, character varying) OWNER TO test;
ALTER FUNCTION updatecontact (integer, character varying, character varying, character varying, character varying, character varying, character varying) OWNER TO test;
ALTER FUNCTION updatedocument (integer, integer, character varying, character varying, character varying, character varying, bytea, character varying, integer) OWNER TO test;
ALTER FUNCTION updateevent (integer, character varying, character varying, timestamp without time zone, character varying, character varying) OWNER TO test;
ALTER FUNCTION updatehtmltext (integer, text, text, text) OWNER TO test;
ALTER FUNCTION updatemodule (integer, integer, character varying, character varying, integer, character varying, boolean) OWNER TO test;
ALTER FUNCTION updatemoduledefinition (integer, character varying, character varying, character varying) OWNER TO test;
ALTER FUNCTION updatemoduleorder (integer, integer, character varying) OWNER TO test;
ALTER FUNCTION updatemodulesetting (integer, character varying, character varying) OWNER TO test;
ALTER FUNCTION updateportalinfo (integer, character varying, boolean) OWNER TO test;
ALTER FUNCTION updaterole (integer, character varying) OWNER TO test;
ALTER FUNCTION updatetaborder (integer, integer) OWNER TO test;
ALTER FUNCTION updateuser (integer, character varying, character varying) OWNER TO test;
ALTER FUNCTION userlogin (character varying, character varying) OWNER TO test;
ALTER FUNCTION deletelink (integer) OWNER TO test;
ALTER FUNCTION getdocuments (integer) OWNER TO test;
ALTER FUNCTION getdocumentcontent (integer) OWNER TO test;
ALTER FUNCTION deleteannouncement (integer) OWNER TO test;
ALTER FUNCTION deletecontact (integer) OWNER TO test;
ALTER FUNCTION deletedocument (integer) OWNER TO test;
ALTER FUNCTION deleteevent (integer) OWNER TO test;
ALTER FUNCTION deletemodule (integer) OWNER TO test;
ALTER FUNCTION deletemoduledefinition (integer) OWNER TO test;
ALTER FUNCTION deleterole (integer) OWNER TO test;
ALTER FUNCTION deletetab (integer) OWNER TO test;
ALTER FUNCTION deleteuser (integer) OWNER TO test;
ALTER FUNCTION deleteuserrole (integer, integer) OWNER TO test;
ALTER FUNCTION adduserrole (integer, integer) OWNER TO test;
ALTER FUNCTION updatetab (integer, integer, integer, character varying, character varying, character varying, boolean) OWNER TO test;
ALTER FUNCTION getnextmessageid (integer) OWNER TO test;
ALTER FUNCTION getprevmessageid (integer) OWNER TO test;
ALTER FUNCTION addmessage (character varying, character varying, integer, character varying, integer) OWNER TO test;
ALTER FUNCTION gettoplevelmessages (integer) OWNER TO test;
ALTER FUNCTION getthreadmessages (character varying) OWNER TO test;
ALTER FUNCTION getsinglemessage (integer) OWNER TO test;
