
GRANT EXECUTE ON FUNCTION addannouncement (integer, character varying, character varying, character varying, character varying, timestamp without time zone, character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getlinks (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getannouncements (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getevents (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getmodulesettings (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION gethtmltext (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getauthroles (integer, integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getcontacts (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getmoduledefinitions (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getportalroles (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getrolemembership (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getrolesbyuser (character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getsingleannouncement (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getsinglecontact (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getsingledocument (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getsingleevent (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getsinglelink (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getsinglemoduledefinition (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getsinglerole (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getsingleuser (character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getusers () TO PUBLIC;
GRANT EXECUTE ON FUNCTION gettabs (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getmodulemoduledefinitions (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getportalsettings (character varying, integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION addcontact (integer, character varying, character varying, character varying, character varying, character varying, character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION addevent (integer, character varying, character varying, timestamp without time zone, character varying, character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION addlink (integer, character varying, character varying, character varying, character varying, integer, character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION addmodule (integer, integer, character varying, character varying, integer, integer, character varying, boolean) TO PUBLIC;
GRANT EXECUTE ON FUNCTION addmoduledefinition (integer, character varying, character varying, character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION addrole (integer, character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION addtab (integer, character varying, integer, character varying, character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION adduser (character varying, character varying, character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION updatelink (integer, character varying, character varying, character varying, character varying, integer, character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION updateannouncement (integer, character varying, character varying, character varying, character varying, timestamp without time zone, character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION updatecontact (integer, character varying, character varying, character varying, character varying, timestamp without time zone, character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION updatecontact (integer, character varying, character varying, character varying, character varying, character varying, character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION updatedocument (integer, integer, character varying, character varying, character varying, character varying, bytea, character varying, integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION updateevent (integer, character varying, character varying, timestamp without time zone, character varying, character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION updatehtmltext (integer, text, text, text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION updatemodule (integer, integer, character varying, character varying, integer, character varying, boolean) TO PUBLIC;
GRANT EXECUTE ON FUNCTION updatemoduledefinition (integer, character varying, character varying, character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION updatemoduleorder (integer, integer, character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION updatemodulesetting (integer, character varying, character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION updateportalinfo (integer, character varying, boolean) TO PUBLIC;
GRANT EXECUTE ON FUNCTION updaterole (integer, character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION updatetaborder (integer, integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION updateuser (integer, character varying, character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION userlogin (character varying, character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION deletelink (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getdocuments (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getdocumentcontent (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION deleteannouncement (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION deletecontact (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION deletedocument (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION deleteevent (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION deletemodule (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION deletemoduledefinition (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION deleterole (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION deletetab (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION deleteuser (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION deleteuserrole (integer, integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION adduserrole (integer, integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION updatetab (integer, integer, integer, character varying, character varying, character varying, boolean) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getnextmessageid (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getprevmessageid (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION addmessage (character varying, character varying, integer, character varying, integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION gettoplevelmessages (integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getthreadmessages (character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION getsinglemessage (integer) TO PUBLIC;
